improve --deploy

diff --git a/bin/pimp b/bin/pimp
--- a/bin/pimp
+++ b/bin/pimp
@@ -29,7 +29,8 @@
         echo      '  pimp --copy @venv <bin>    # set x-permissions & copy <bin> files to @venv/bin'
         echo      '  pimp --deploy              # deploy files in .pimp/deploy into binary system folder'
         echo      '  pimp --deploy <bin>        # deploy files in .pimp/deploy into given <bin> folder'
-        echo      '  pimp --init @venv          # init a .pimp directory with setup/cleanup samples'
+        echo      '  pimp --init                # init a .pimp directory'
+        echo      '  pimp --init @venv          # init a .pimp dir for @venv with setup/cleanup samples'
         echo      '  pimp --install             # install pimp in $BIN directory'
         echo      '  pimp --install pimp <bin>  # install pimp in <bin> directory'
         echo      '  pimp --path <dir>          # examine path of directory in upward hierarchy'
@@ -47,7 +48,7 @@
 #===============================================================================
 
    if [ "$*" == "--version" ] || [ "$*" == "--v" ]; then
-      echo "1.0.0c";
+      echo "1.0.0f";
       return 0 2>/dev/null || exit 0  # safe return/exit
    fi
 
@@ -237,13 +238,22 @@
 #===============================================================================
 
    if [ "$1" == "--deploy" ] && [ "$3" == "" ]; then
-      if [ ! -f .pimp/deploy ]; then
+      PIMP=`pimp --path .pimp`
+      ROOT=$(dirname $PIMP)
+
+      if [ "$PIMP" == "" ]; then
          bash pimp ---r "error: pimp $*" >&2
-         echo           "       no deployment list (file .pimp/deploy) provided" >&2
+         echo           "       no .pimp directory found" >&2
          exit 1
       fi
 
-      if [ "`cat .pimp/deploy`" == "" ]; then
+      if [ ! -f $PIMP/deploy ]; then
+         bash pimp ---r "error: pimp $*" >&2
+         echo           "       no deployment list (file $PIMP/deploy) provided" >&2
+         exit 1
+      fi
+
+      if [ "`cat $PIMP/deploy`" == "" ]; then
          pimp ---g "=== empty deploy list (nothing to deploy)"
          exit 0
       fi
@@ -290,12 +300,12 @@
          # actual deployment
 
       bash pimp ---g "=== deploying tools in $BIN ..."
-      SRC=.pimp/bin
+      SRC=$PIMP/bin
 
 			for TOOL in $TOOLS
 			do
          FILE="${TOOL##*/}"
-			   VSRC=`bash $TOOL --version 2>/dev/null`
+			   VSRC=`bash $ROOT/$TOOL --version 2>/dev/null`
 			   VDST=`bash $BIN/$FILE --version 2>/dev/null`
 
 	       if [ "$VDST" == "" ] && [ ! -f $BIN/$FILE ]; then
@@ -308,8 +318,8 @@
 	       if [ "$VSRC" != '???' ] && [ "$VDST" != '???' ]; then
 	          if [ "$VSRC" != "$VDST" ]; then
                if [ "$ERR" == "0" ]; then
-   	              echo "    cp $TOOL $BIN;  chmod +x $BIN/$FILE"
-	                cp $TOOL $BIN;  chmod +x $BIN/$FILE
+   	              echo "    cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE"
+	                cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE
                else
    	              echo "    sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE"
 	                sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE
@@ -317,7 +327,7 @@
 	          fi
 	       else
 	          pimp ---m "    note: not updating $TOOL"
-	          pimp ---m "          reason: missing version information ($VSRC => $VDST)"
+	          pimp ---m "          reason: missing version information (upgrade version $VSRC to $VDST)"
 	          pimp ---m "          (you may manually delete the installed tool)"
 	       fi
 			done
@@ -331,17 +341,20 @@
 #===============================================================================
 
    if [ "$1" == "---deploy-status" ] && [ "$2" != "" ] && [ "$3" == "" ]; then
+      PIMP=`pimp --path .pimp`
+      ROOT=$(dirname $PIMP)
+
       BIN=$2
-      SRC=.pimp/bin
+      SRC=$PIMP/bin
 
       ec -g "deployment status:" 1>&2
       ec -y "tools to be deployed into $BIN:" 1>&2
 
       TOOLS=''
-      for TOOL in `cat .pimp/deploy`
+      for TOOL in `cat $PIMP/deploy`
       do
          FILE="${TOOL##*/}"
-         VSRC=`bash $TOOL --version 2>/dev/null`
+         VSRC=`bash $ROOT/$TOOL --version 2>/dev/null`
          VDST=`bash $BIN/$FILE --version 2>/dev/null`
 
          if [ "$VDST" == "" ] && [ ! -f $BIN/$FILE ]; then
@@ -372,68 +385,78 @@
    fi
 
 #===============================================================================
+# pimp --init        # init a .pimp directory'
 # pimp --init @venv  # init a .pimp directory with setup/cleanup samples
 #===============================================================================
 
    if [ "$1" == "--init" ] && [ "$3" == "" ]; then
+      PIMP=.pimp
       VENV=$2
-      if [ "$VENV" == "" ]; then
-         pimp ---r "error: pimp $*" >&2
-         echo      "       missing arg2 (name of virtual environment to be created)" >&2
-         exit 1
-      fi
+      #if [ "$VENV" == "" ]; then
+      #   pimp ---r "error: pimp $*" >&2
+      #   echo      "       missing arg2 (name of virtual environment to be created)" >&2
+      #   exit 1
+      #fi
 
-      if [ -d ".pimp" ]; then
+      if [ -d "$PIMP" ]; then
          pimp ---r "error: pimp $*" >&2
-         echo      "       directory .pimp already existing (stop processing)" >&2
+         echo      "       directory $PIMP already existing (stop processing)" >&2
          exit 1
       fi
 
       pimp ---g "=== initializing .pimp directory ..."
+
          # make .pimp and .pimp/bin directories and provide .pimp/venv
 
-      mkdir .pimp || exit 1
-      PIMPBIN=.pimp/bin
-      mkdir $PIMPBIN || exit 1
-      echo $2 >.pimp/venv
-
-         # provide a setup sample
-
-      echo '#!/bin/bash' >$PIMPBIN/setup.sh
-      echo '# setup (setup script for virtual environment)' >>$PIMPBIN/setup.sh
-      echo '' >>$PIMPBIN/setup.sh
-      echo "echo '=== setup virtual environment ...'" >>$PIMPBIN/setup.sh
-
-         # provide a cleanup sample
-
-      echo '#!/bin/bash' >$PIMPBIN/cleanup.sh
-      echo '# setup (cleanup script for virtual environment)' >>$PIMPBIN/cleanup.sh
-      echo '' >>$PIMPBIN/cleanup.sh
-      echo "echo '=== cleanup virtual environment ...'" >>$PIMPBIN/cleanup.sh
+      mkdir $PIMP || exit 1
 
          # provide consign and deploy skeletons
 
-      touch .pimp/consign
-      touch .pimp/deploy
+      touch $PIMP/consign
+      touch $PIMP/deploy
 
-         # add virtual environment name to .gitignore
+         # for empty arg2 we are done
 
-      if [ -d ".git" ]; then
-         if [ -f ".gitignore" ]; then
-            cat .gitignore | grep "$VENV" >/dev/null && exit 0  # nothing to do
-         fi
+      if [ "$VENV" == "" ]; then exit 0; fi
 
-         read -p "shall I add $VENV to .gitignore [Y/n]?" ANS
- 		     if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
-				   exit 0
-				 fi
+         # for nonempty arg2 we continue preparing venv creation
 
-         pimp ---g "=== adding $VENV to .gitignore"
-         echo '' >>.gitignore
-         echo '# virtual environment folder' >>.gitignore
-         echo "$VENV" >>.gitignore
-      fi
-      exit 0
+		  PIMPBIN=$PIMP/bin
+		  mkdir $PIMPBIN || exit 1
+		  echo $2 >$PIMP/venv
+
+		     # provide a setup sample
+
+		  echo '#!/bin/bash' >$PIMPBIN/setup.sh
+		  echo '# setup (setup script for virtual environment)' >>$PIMPBIN/setup.sh
+		  echo '' >>$PIMPBIN/setup.sh
+		  echo "echo '=== setup virtual environment ...'" >>$PIMPBIN/setup.sh
+
+		     # provide a cleanup sample
+
+		  echo '#!/bin/bash' >$PIMPBIN/cleanup.sh
+		  echo '# setup (cleanup script for virtual environment)' >>$PIMPBIN/cleanup.sh
+		  echo '' >>$PIMPBIN/cleanup.sh
+		  echo "echo '=== cleanup virtual environment ...'" >>$PIMPBIN/cleanup.sh
+
+		     # add virtual environment name to .gitignore
+
+		  if [ -d ".git" ]; then
+		     if [ -f ".gitignore" ]; then
+		       cat .gitignore | grep "$VENV" >/dev/null && exit 0  # nothing to do
+		     fi
+
+		     read -p "shall I add $VENV to .gitignore [Y/n]?" ANS
+		     if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
+		        exit 0
+		     fi
+
+ 		     pimp ---g "=== adding $VENV to .gitignore"
+		     echo '' >>.gitignore
+		     echo '# virtual environment folder' >>.gitignore
+		     echo "$VENV" >>.gitignore
+		  fi
+		  exit 0
    fi
 
 #===============================================================================
@@ -569,18 +592,25 @@ fi
 #===============================================================================
 
    if [ "$*" == "--zephyr" ]; then
-      if [ ! -d ".pimp" ]; then
+      PIMP=`pimp --path .pimp`
+      if [ "$PIMP" == "" ]; then
+         bash pimp ---r "error: pimp $*" >&2
+         echo           "       no .pimp directory found" >&2
+         exit 1
+      fi
+
+      if [ ! -d "$PIMP" ]; then
          pimp ---r "error: pimp $*" >&2
          echo      "       missing .pimp directory" >&2
          echo      "       => consider: pimp --init <venv>" >&2
          exit 1
       fi
-      if [ ! -f ".pimp/bin/setup.sh" ]; then
+      if [ ! -f "$PIMP/bin/setup.sh" ]; then
          pimp ---r "error: pimp $*" >&2
          echo      "       missing .pimp/bin/setup.sh script" >&2
          exit 1
       fi
-      if [ ! -f ".pimp/bin/cleanup.sh" ]; then
+      if [ ! -f "$PIMP/bin/cleanup.sh" ]; then
          pimp ---r "error: pimp $*" >&2
          echo      "       missing .pimp/bin/cleanup.sh script" >&2
          exit 1
@@ -588,13 +618,13 @@ fi
 
       pimp ---g "=== pimping .pimp for zephyr"
 
-      echo '' >>.pimp/bin/setup.sh
-      echo '# setting ZEPHYR_BASE' >>.pimp/bin/setup.sh
-      echo "export ZEPHYR_BASE=`pwd`/zephyr" >>.pimp/bin/setup.sh
+      echo '' >>$PIMP/bin/setup.sh
+      echo '# setting ZEPHYR_BASE' >>$PIMP/bin/setup.sh
+      echo "export ZEPHYR_BASE=`pwd`/zephyr" >>$PIMP/bin/setup.sh
 
-      echo '' >>.pimp/bin/cleanup.sh
-      echo '# unsetting ZEPHYR_BASE' >>.pimp/bin/cleanup.sh
-      echo "unset ZEPHYR_BASE" >>.pimp/bin/cleanup.sh
+      echo '' >>$PIMP/bin/cleanup.sh
+      echo '# unsetting ZEPHYR_BASE' >>$PIMP/bin/cleanup.sh
+      echo "unset ZEPHYR_BASE" >>$PIMP/bin/cleanup.sh
       exit 0
    fi
 
@@ -666,13 +696,14 @@ fi
 #===============================================================================
 
    if [ "$*" == "" ]; then
+      PIMP=.pimp
       VENV=`pimp --venv`
 
          # check existence of virtual environment, and occasionally create
 
       if [ "$VENV" == "" ]; then
-         if [ -f .pimp/venv ]; then
-            VENV=`cat .pimp/venv`
+         if [ -f $PIMP/venv ]; then
+            VENV=`cat $PIMP/venv`
             pimp ---y "virtual environment not existing!"
 
             read -p "shall I create virtual environment $VENV [Y/n]?" ANS
