put files to deploy into bin directory

diff --git a/bin/pimp b/bin/pimp
--- a/bin/pimp
+++ b/bin/pimp
@@ -10,13 +10,14 @@
    if [ "$*" == "-?" ] || [ "$*" == "--help" ] || [ "$*" == "--?" ]; then
       pimp ---g   "pimp virtual environment (version `pimp --version`)"
       pimp ---y   'usage: pimp [-ci?] [--<opt>] [<venv>] [<bin>]'
-      echo        '  pimp                       # pimp, consign and install files in virtual environment'
       echo        '  . pimp                     # pimp, consign, install and activate virtual environment'
-      echo        '  pimp -c                    # consign files according to .pimp/consign list'
-      echo        '  pimp -i                    # install consigned files in virtual environment'
-      echo        '  pimp -d                    # consign and deploy binaries to $BIN directory'
       echo        '  pimp @venv                 # pimp @venv to support setup/cleanup'
       echo        '  pimp @venv .pimp/bin       # also install binaries of .pimp/bin in @venv'
+      echo        '  pimp -d                    # deploy files in .pimp/deploy into binary system folder'
+      echo        '  pimp -d <bin>              # deploy files in .pimp/deploy into given <bin> folder'
+      echo        '  pimp -i                    # init a .pimp directory'
+      echo        '  pimp -i @venv              # init a .pimp dir for @venv with setup/cleanup samples'
+      echo        '  pimp -m                    # init a sample west manifest directory'
       echo        '  pimp -?                    # show usage'
       echo        '  pimp --help                # comprehensive help'
       echo        '  pimp --version             # print version'
@@ -244,103 +245,105 @@
 # pimp --deploy <bin> # deploy files into given <bin> folder'
 #===============================================================================
 
-   if [ "$1" == "--deploy" ] && [ "$3" == "" ]; then
-      PIMP=`pimp --path .pimp`
-      ROOT=$(dirname $PIMP)
+   if [ "$1" == "--deploy" ] || [ "$1" == "-d" ]; then
+      if [ "$3" == "" ]; then
+         PIMP=`pimp --path .pimp`
+         ROOT=$(dirname $PIMP)
 
-      if [ "$PIMP" == "" ]; then
-         bash pimp ---r "error: pimp $*" >&2
-         echo           "       no .pimp directory found" >&2
-         exit 1
-      fi
+         if [ "$PIMP" == "" ]; then
+            bash pimp ---r "error: pimp $*" >&2
+            echo           "       no .pimp directory found" >&2
+            exit 1
+         fi
 
-      if [ ! -f $PIMP/deploy ]; then
-         bash pimp ---r "error: pimp $*" >&2
-         echo           "       no deployment list (file $PIMP/deploy) provided" >&2
-         exit 1
-      fi
+         if [ ! -f $PIMP/deploy ]; then
+            bash pimp ---r "error: pimp $*" >&2
+            echo           "       no deployment list (file $PIMP/deploy) provided" >&2
+            exit 1
+         fi
 
-      if [ "`cat $PIMP/deploy`" == "" ]; then
-         pimp ---g "=== empty deploy list (nothing to deploy)"
-         exit 0
-      fi
-
-         # if arg2 is not provided we select target directory from a list
-
-      if [ "$2" == "" ]; then
-         bash pimp ---y "select target directory for deployment:"
-         LIST=`pimp --directories`
-	       select BIN in $LIST
-	       do
-            pimp --deploy $BIN
+         if [ "`cat $PIMP/deploy`" == "" ]; then
+            pimp ---g "=== empty deploy list (nothing to deploy)"
             exit 0
-         done
-         exit 1
-      fi
+         fi
 
-         # otherwise we use arg2 as target directory
+            # if arg2 is not provided we select target directory from a list
 
-      BIN=$2
+         if [ "$2" == "" ]; then
+            bash pimp ---y "select target directory for deployment:"
+            LIST=`pimp --directories`
+	          select BIN in $LIST
+	          do
+               pimp --deploy $BIN
+               exit 0
+            done
+            exit 1
+         fi
 
-         # we need to examine whether target directory is protected
+            # otherwise we use arg2 as target directory
 
-      ERR="0"
-      touch $BIN/_junk_ >/dev/null || ERR="1"
-      rm -f $BIN/_junk_ >/dev/null
+         BIN=$2
 
-               # first show deployment status
+            # we need to examine whether target directory is protected
 
-      TOOLS=`pimp ---deploy-status $BIN`
-      if [ "$TOOLS" == "" ]; then
-         pimp ---g "everything up-to-date (no further deployment action)"
+         ERR="0"
+         touch $BIN/_junk_ >/dev/null || ERR="1"
+         rm -f $BIN/_junk_ >/dev/null
+
+            # first show deployment status
+
+         TOOLS=`pimp ---deploy-status $BIN`
+         if [ "$TOOLS" == "" ]; then
+            pimp ---g "everything up-to-date (no further deployment action)"
+            exit 0
+         fi
+
+            # prompt to confirm deployment
+
+         pimp ---y "confirm deployment!"
+         read -p "go ahead [Y/n]?" ANS
+ 		     if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
+			      exit 0
+		     fi
+
+            # actual deployment
+
+         bash pimp ---g "=== deploying tools in $BIN ..."
+         SRC=$PIMP/bin
+
+			   for TOOL in $TOOLS
+			   do
+            FILE="${TOOL##*/}"
+			      VSRC=`bash $ROOT/$TOOL --version 2>/dev/null`
+			      VDST=`bash $BIN/$FILE --version 2>/dev/null`
+
+	          if [ "$VDST" == "" ] && [ ! -f $BIN/$FILE ]; then
+	             VDST='not installed'
+	          fi
+
+	          if [ "$VSRC" == "" ]; then VSRC='???'; fi
+	          if [ "$VDST" == "" ]; then VDST='???'; fi
+
+	          if [ "$VSRC" != '???' ] && [ "$VDST" != '???' ]; then
+	             if [ "$VSRC" != "$VDST" ]; then
+                  if [ "$ERR" == "0" ]; then
+   	                 echo "    cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE"
+	                   cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE
+                  else
+   	                 echo "    sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE"
+	                   sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE
+                  fi
+	             fi
+	          else
+	             pimp ---m "    note: not updating $TOOL"
+	             pimp ---m "          reason: missing version information (upgrade version $VSRC to $VDST)"
+	             pimp ---m "          (you may manually delete the installed tool)"
+	          fi
+			   done
+
+         pimp ---g "=== deployment complete!"
          exit 0
       fi
-
-         # prompt to confirm deployment
-
-      pimp ---y "confirm deployment!"
-      read -p "go ahead [Y/n]?" ANS
- 		  if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
-			   exit 0
-		  fi
-
-         # actual deployment
-
-      bash pimp ---g "=== deploying tools in $BIN ..."
-      SRC=$PIMP/bin
-
-			for TOOL in $TOOLS
-			do
-         FILE="${TOOL##*/}"
-			   VSRC=`bash $ROOT/$TOOL --version 2>/dev/null`
-			   VDST=`bash $BIN/$FILE --version 2>/dev/null`
-
-	       if [ "$VDST" == "" ] && [ ! -f $BIN/$FILE ]; then
-	          VDST='not installed'
-	       fi
-
-	       if [ "$VSRC" == "" ]; then VSRC='???'; fi
-	       if [ "$VDST" == "" ]; then VDST='???'; fi
-
-	       if [ "$VSRC" != '???' ] && [ "$VDST" != '???' ]; then
-	          if [ "$VSRC" != "$VDST" ]; then
-               if [ "$ERR" == "0" ]; then
-   	              echo "    cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE"
-	                cp $ROOT/$TOOL $BIN;  chmod +x $BIN/$FILE
-               else
-   	              echo "    sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE"
-	                sudo cp $TOOL $BIN;  sudo chmod +x $BIN/$FILE
-               fi
-	          fi
-	       else
-	          pimp ---m "    note: not updating $TOOL"
-	          pimp ---m "          reason: missing version information (upgrade version $VSRC to $VDST)"
-	          pimp ---m "          (you may manually delete the installed tool)"
-	       fi
-			done
-
-      pimp ---g "=== deployment complete!"
-      exit 0
    fi
 
 #===============================================================================
@@ -392,78 +395,80 @@
    fi
 
 #===============================================================================
-# pimp --init        # init a .pimp directory'
-# pimp --init @venv  # init a .pimp directory with setup/cleanup samples
+# pimp --init  (pimp -i)            # init a .pimp directory'
+# pimp --init @venv (pimp -i @venv) # init a .pimp directory with setup/cleanup samples
 #===============================================================================
 
-   if [ "$1" == "--init" ] && [ "$3" == "" ]; then
-      PIMP=.pimp
-      VENV=$2
-      #if [ "$VENV" == "" ]; then
-      #   pimp ---r "error: pimp $*" >&2
-      #   echo      "       missing arg2 (name of virtual environment to be created)" >&2
-      #   exit 1
-      #fi
+   if [ "$1" == "--init" ] || [ "$1" == "-i" ]; then
+      if [ "$3" == "" ]; then
+         PIMP=.pimp
+         VENV=$2
+         #if [ "$VENV" == "" ]; then
+         #   pimp ---r "error: pimp $*" >&2
+         #   echo      "       missing arg2 (name of virtual environment to be created)" >&2
+         #   exit 1
+         #fi
 
-      if [ -d "$PIMP" ]; then
-         pimp ---r "error: pimp $*" >&2
-         echo      "       directory $PIMP already existing (stop processing)" >&2
-         exit 1
+         if [ -d "$PIMP" ]; then
+            pimp ---r "error: pimp $*" >&2
+            echo      "       directory $PIMP already existing (stop processing)" >&2
+            exit 1
+         fi
+
+         pimp ---g "=== initializing .pimp directory ..."
+
+            # make .pimp and .pimp/bin directories and provide .pimp/venv
+
+         mkdir $PIMP || exit 1
+
+            # provide consign and deploy skeletons
+
+         touch $PIMP/consign
+         touch $PIMP/deploy
+
+            # for empty arg2 we are done
+
+         if [ "$VENV" == "" ]; then exit 0; fi
+
+            # for nonempty arg2 we continue preparing venv creation
+
+		     PIMPBIN=$PIMP/bin
+		     mkdir $PIMPBIN || exit 1
+		     echo $2 >$PIMP/venv
+
+		        # provide a setup sample
+
+		     echo '#!/bin/bash' >$PIMPBIN/setup.sh
+		     echo '# setup (setup script for virtual environment)' >>$PIMPBIN/setup.sh
+		     echo '' >>$PIMPBIN/setup.sh
+		     echo "echo '=== setup virtual environment ...'" >>$PIMPBIN/setup.sh
+
+		        # provide a cleanup sample
+
+		     echo '#!/bin/bash' >$PIMPBIN/cleanup.sh
+		     echo '# setup (cleanup script for virtual environment)' >>$PIMPBIN/cleanup.sh
+		     echo '' >>$PIMPBIN/cleanup.sh
+		     echo "echo '=== cleanup virtual environment ...'" >>$PIMPBIN/cleanup.sh
+
+		        # add virtual environment name to .gitignore
+
+		     if [ -d ".git" ]; then
+		        if [ -f ".gitignore" ]; then
+		           cat .gitignore | grep "$VENV" >/dev/null && exit 0  # nothing to do
+		        fi
+
+		        read -p "shall I add $VENV to .gitignore [Y/n]?" ANS
+		        if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
+		           exit 0
+		        fi
+
+ 		        pimp ---g "=== adding $VENV to .gitignore"
+		        echo '' >>.gitignore
+		        echo '# virtual environment folder' >>.gitignore
+		        echo "$VENV" >>.gitignore
+		     fi
+		     exit 0
       fi
-
-      pimp ---g "=== initializing .pimp directory ..."
-
-         # make .pimp and .pimp/bin directories and provide .pimp/venv
-
-      mkdir $PIMP || exit 1
-
-         # provide consign and deploy skeletons
-
-      touch $PIMP/consign
-      touch $PIMP/deploy
-
-         # for empty arg2 we are done
-
-      if [ "$VENV" == "" ]; then exit 0; fi
-
-         # for nonempty arg2 we continue preparing venv creation
-
-		  PIMPBIN=$PIMP/bin
-		  mkdir $PIMPBIN || exit 1
-		  echo $2 >$PIMP/venv
-
-		     # provide a setup sample
-
-		  echo '#!/bin/bash' >$PIMPBIN/setup.sh
-		  echo '# setup (setup script for virtual environment)' >>$PIMPBIN/setup.sh
-		  echo '' >>$PIMPBIN/setup.sh
-		  echo "echo '=== setup virtual environment ...'" >>$PIMPBIN/setup.sh
-
-		     # provide a cleanup sample
-
-		  echo '#!/bin/bash' >$PIMPBIN/cleanup.sh
-		  echo '# setup (cleanup script for virtual environment)' >>$PIMPBIN/cleanup.sh
-		  echo '' >>$PIMPBIN/cleanup.sh
-		  echo "echo '=== cleanup virtual environment ...'" >>$PIMPBIN/cleanup.sh
-
-		     # add virtual environment name to .gitignore
-
-		  if [ -d ".git" ]; then
-		     if [ -f ".gitignore" ]; then
-		       cat .gitignore | grep "$VENV" >/dev/null && exit 0  # nothing to do
-		     fi
-
-		     read -p "shall I add $VENV to .gitignore [Y/n]?" ANS
-		     if [ "$ANS" != "Y" ] && [ "$ANS" != "y" ] && [ "$ANS" != "" ]; then
-		        exit 0
-		     fi
-
- 		     pimp ---g "=== adding $VENV to .gitignore"
-		     echo '' >>.gitignore
-		     echo '# virtual environment folder' >>.gitignore
-		     echo "$VENV" >>.gitignore
-		  fi
-		  exit 0
    fi
 
 #===============================================================================
@@ -514,10 +519,10 @@
    fi
 
 #===============================================================================
-# pimp --manifest   # init a sample west manifest directory'
+# pimp --manifest (pimp -m)   # init a sample west manifest directory'
 #===============================================================================
 
-   if [ "$*" == "--manifest" ]; then
+   if [ "$*" == "--manifest" ] || [ "$*" == "-m" ]; then
       PIMP=`pimp --path .pimp`
       ROOT=$(dirname $PIMP)
       MANIFEST=$ROOT/manifest
